apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-webhook-run
  namespace: getting-started
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
    - name: GitHubOrg
      value: "cakiem8x"
    - name: GitHubUser
      value: "cakiem8x"
    - name: GitHubRepo
      value: "podinfo"
    - name: GitHubSecretName
      value: webhook-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: getting-started.cunpolo.fun
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
