apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-istio-gateway-virtualservice-run
  namespace: getting-started
spec:
  taskRef:
    name: create-istio-gateway-virtualservice
  inputs:
    params:
      - name: TLScredentialName
        value: letsencrypt-staging
      - name: ExternalDomain
        value: getting-started.cunpolo.fun
      - name: Service
        value: el-getting-started-listener
      - name: ServicePort
        value: '8080'
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
